apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - "RequestReceived"
rules:
- level: Metadata
  resources:
  - resources: ["pods", "configmaps"]
    namespaces: ["omega", "citadel", "eden-prime"]
